# -*- coding: utf-8 -*-
"""indexing_documents.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_KqCxxRgCicZf7Fythf3FgixuNU-Hyrs
"""

import pandas as pd
from xml.dom import minidom
import os

from elasticsearch import Elasticsearch

es = Elasticsearch("http://localhost:9200")
es.info()

position_start_id = 6 

def id_converter(id):
    id = id[position_start_id:]
    return id

def text_converter(text):
    text = text.replace("\"", " ")
    text = text.replace("\n", " ")
    return text
#put here the path for regis-collection-master
path_to_data = 'regis-collection/documents'

files_names = os.listdir(path_to_data)

#es.indices.create(index="regis_collection")

files_names

from elasticsearch.helpers import bulk

bulk_data = []

for name_xml_file in files_names:
    file_path = path_to_data + "/"+name_xml_file
    # parse an xml file by name
    file = minidom.parse(file_path)

    #use getElementsByTagName() to get tag
    document = file.getElementsByTagName('field')

    x = id_converter(document[0].firstChild.data)
    filename = document[1].firstChild.data
    text = text_converter(document[3].firstChild.data)
    
    doc = {
        "id": x,
        "filename": filename,
        "text": text
    }
    
    es.index(index="regis_collection", id=x, document=doc)

es.indices.refresh(index="regis_collection")
es.cat.count(index="regis_collection", format="json")

es.get(index="regis_collection", id=x)

